# Generated by Django 3.1.4 on 2021-04-30 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shortURL',
            fields=[
                ('key', models.CharField(blank=True, default='a3436d', editable=False, max_length=8, primary_key=True, serialize=False)),
                ('url', models.TextField()),
            ],
        ),
    ]
